# This is a basic workflow to help you get started with Actions

name: build-docker
run-name: ${{ github.actor }} build docker image

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  username: ${{ github.actor }}
  password: ${{ secrets.GITHUB_TOKEN }}
  DEPLOY_TAG: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: $REGISTRY
          username: $username
          password: $password

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker build . --tag ghcr.io/VladislavBodikov/mongodb:$DEPLOY_TAG
          docker run ghcr.io/VladislavBodikov/mongodb:$DEPLOY_TAG
          docker push ghcr.io/VladislavBodikov/mongodb:$DEPLOY_TAG
